ALTER TABLE NODE ADD TYPE_ID INTEGER;

UPDATE NODE
SET TYPE_ID = 1 WHERE ID = 5 OR ID = 1 OR ID = 4;

UPDATE NODE
SET TYPE_ID = 3 WHERE ID = 8;

UPDATE NODE
SET TYPE_ID = 2 WHERE ID = 2;

UPDATE NODE
SET TYPE_ID = 4 WHERE ID = 3;

